import React from 'react';
import { Space, Avatar, Typography } from 'antd';
import {
    HomeOutlined, SketchOutlined, FileDoneOutlined, ShoppingOutlined, BarChartOutlined, DollarOutlined, TeamOutlined, GiftOutlined,
    CheckCircleOutlined, UserOutlined, CloudUploadOutlined, AuditOutlined, ArrowRightOutlined, ArrowLeftOutlined, AlertOutlined,
    FileAddOutlined, FileSearchOutlined, FileProtectOutlined, FileExclamationOutlined, FileSyncOutlined, FileTextOutlined,
    FileUnknownOutlined, FileImageOutlined, FileZipOutlined, FilePdfOutlined, FileMarkdownOutlined, FileWordOutlined, FileExcelOutlined,
    BugOutlined, BulbOutlined, CalculatorOutlined, CommentOutlined, CrownOutlined, EnvironmentOutlined, EyeOutlined, FieldTimeOutlined,
    FireOutlined, GlobalOutlined, LockOutlined, MailOutlined, PhoneOutlined, PrinterOutlined,
    SafetyCertificateOutlined, ScheduleOutlined, SearchOutlined, SettingOutlined, ShareAltOutlined, ShoppingCartOutlined,
    TruckOutlined, TranslationOutlined, UserAddOutlined, UserDeleteOutlined, UserSwitchOutlined,
    UsergroupAddOutlined, UsergroupDeleteOutlined, WalletOutlined, WechatOutlined, WhatsAppOutlined, YoutubeOutlined,
    VerifiedOutlined, WifiOutlined, WarningOutlined, UsbOutlined, WomanOutlined, ThunderboltOutlined, StarOutlined, SunOutlined,
    ProfileOutlined, ProductOutlined, MenuOutlined, LaptopOutlined, HistoryOutlined, GoldOutlined, FieldBinaryOutlined,
    ExperimentOutlined, DatabaseOutlined, DashboardOutlined, CoffeeOutlined, CloudOutlined, CameraOutlined, CarOutlined,
    AppstoreOutlined, ApartmentOutlined, BarcodeOutlined, BankOutlined, BookOutlined, FullscreenOutlined, FullscreenExitOutlined,
    RetweetOutlined, QuestionCircleOutlined, InfoOutlined, ClockCircleOutlined, DeleteOutlined, RadarChartOutlined, SlidersOutlined,
    AppleOutlined, AndroidOutlined, WindowsOutlined, DingtalkOutlined, DropboxOutlined, SlackOutlined, RedditOutlined, PythonOutlined,
    AccountBookOutlined, AimOutlined, ApiOutlined, AudioOutlined, BorderlessTableOutlined, ClearOutlined, ContactsOutlined,
    DislikeOutlined, DisconnectOutlined, FieldNumberOutlined, FolderViewOutlined, FlagOutlined, FrownOutlined, HddOutlined, HeartOutlined,
    InsuranceOutlined, LikeOutlined, LinkOutlined, MoonOutlined, MoneyCollectOutlined, OneToOneOutlined, PercentageOutlined, PushpinOutlined,
    QrcodeOutlined, SafetyOutlined, SkinOutlined, TableOutlined, ToolOutlined, TrademarkOutlined, ToTopOutlined, SplitCellsOutlined,
    MedicineBoxOutlined, LineOutlined, HourglassOutlined, HolderOutlined, FunctionOutlined, ForkOutlined, ExportOutlined
} from '@ant-design/icons';

// 圖標映射表
const iconMapping = {
    AccountBookOutlined: <AccountBookOutlined />,
    AimOutlined: <AimOutlined />,
    AlertOutlined: <AlertOutlined />,
    AndroidOutlined: <AndroidOutlined />,
    ApartmentOutlined: <ApartmentOutlined />,
    ApiOutlined: <ApiOutlined />,
    AppleOutlined: <AppleOutlined />,
    AppstoreOutlined: <AppstoreOutlined />,
    ArrowLeftOutlined: <ArrowLeftOutlined />,
    ArrowRightOutlined: <ArrowRightOutlined />,
    AudioOutlined: <AudioOutlined />,
    AuditOutlined: <AuditOutlined />,
    BankOutlined: <BankOutlined />,
    BarChartOutlined: <BarChartOutlined />,
    BarcodeOutlined: <BarcodeOutlined />,
    BookOutlined: <BookOutlined />,
    BorderlessTableOutlined: <BorderlessTableOutlined />,
    BugOutlined: <BugOutlined />,
    BulbOutlined: <BulbOutlined />,
    CalculatorOutlined: <CalculatorOutlined />,
    CameraOutlined: <CameraOutlined />,
    CarOutlined: <CarOutlined />,
    CheckCircleOutlined: <CheckCircleOutlined />,
    ClearOutlined: <ClearOutlined />,
    ClockCircleOutlined: <ClockCircleOutlined />,
    CloudOutlined: <CloudOutlined />,
    CloudUploadOutlined: <CloudUploadOutlined />,
    CoffeeOutlined: <CoffeeOutlined />,
    CommentOutlined: <CommentOutlined />,
    ContactsOutlined: <ContactsOutlined />,
    CrownOutlined: <CrownOutlined />,
    DashboardOutlined: <DashboardOutlined />,
    DatabaseOutlined: <DatabaseOutlined />,
    DeleteOutlined: <DeleteOutlined />,
    DingtalkOutlined: <DingtalkOutlined />,
    DisconnectOutlined: <DisconnectOutlined />,
    DislikeOutlined: <DislikeOutlined />,
    DollarOutlined: <DollarOutlined />,
    DropboxOutlined: <DropboxOutlined />,
    EnvironmentOutlined: <EnvironmentOutlined />,
    ExperimentOutlined: <ExperimentOutlined />,
    ExportOutlined: <ExportOutlined />,
    EyeOutlined: <EyeOutlined />,
    FieldBinaryOutlined: <FieldBinaryOutlined />,
    FieldNumberOutlined: <FieldNumberOutlined />,
    FieldTimeOutlined: <FieldTimeOutlined />,
    FileAddOutlined: <FileAddOutlined />,
    FileDoneOutlined: <FileDoneOutlined />,
    FileExcelOutlined: <FileExcelOutlined />,
    FileExclamationOutlined: <FileExclamationOutlined />,
    FileImageOutlined: <FileImageOutlined />,
    FileMarkdownOutlined: <FileMarkdownOutlined />,
    FilePdfOutlined: <FilePdfOutlined />,
    FileProtectOutlined: <FileProtectOutlined />,
    FileSearchOutlined: <FileSearchOutlined />,
    FileSyncOutlined: <FileSyncOutlined />,
    FileTextOutlined: <FileTextOutlined />,
    FileUnknownOutlined: <FileUnknownOutlined />,
    FileWordOutlined: <FileWordOutlined />,
    FileZipOutlined: <FileZipOutlined />,
    FireOutlined: <FireOutlined />,
    FlagOutlined: <FlagOutlined />,
    FolderViewOutlined: <FolderViewOutlined />,
    ForkOutlined: <ForkOutlined />,
    FrownOutlined: <FrownOutlined />,
    FullscreenExitOutlined: <FullscreenExitOutlined />,
    FullscreenOutlined: <FullscreenOutlined />,
    FunctionOutlined: <FunctionOutlined />,
    GiftOutlined: <GiftOutlined />,
    GlobalOutlined: <GlobalOutlined />,
    GoldOutlined: <GoldOutlined />,
    HddOutlined: <HddOutlined />,
    HeartOutlined: <HeartOutlined />,
    HistoryOutlined: <HistoryOutlined />,
    HolderOutlined: <HolderOutlined />,
    HomeOutlined: <HomeOutlined />,
    HourglassOutlined: <HourglassOutlined />,
    InfoOutlined: <InfoOutlined />,
    InsuranceOutlined: <InsuranceOutlined />,
    LaptopOutlined: <LaptopOutlined />,
    LikeOutlined: <LikeOutlined />,
    LineOutlined: <LineOutlined />,
    LinkOutlined: <LinkOutlined />,
    LockOutlined: <LockOutlined />,
    MailOutlined: <MailOutlined />,
    MedicineBoxOutlined: <MedicineBoxOutlined />,
    MenuOutlined: <MenuOutlined />,
    MoneyCollectOutlined: <MoneyCollectOutlined />,
    MoonOutlined: <MoonOutlined />,
    OneToOneOutlined: <OneToOneOutlined />,
    PercentageOutlined: <PercentageOutlined />,
    PhoneOutlined: <PhoneOutlined />,
    PrinterOutlined: <PrinterOutlined />,
    ProductOutlined: <ProductOutlined />,
    ProfileOutlined: <ProfileOutlined />,
    PushpinOutlined: <PushpinOutlined />,
    PythonOutlined: <PythonOutlined />,
    QrcodeOutlined: <QrcodeOutlined />,
    QuestionCircleOutlined: <QuestionCircleOutlined />,
    RadarChartOutlined: <RadarChartOutlined />,
    RedditOutlined: <RedditOutlined />,
    RetweetOutlined: <RetweetOutlined />,
    SafetyCertificateOutlined: <SafetyCertificateOutlined />,
    SafetyOutlined: <SafetyOutlined />,
    ScheduleOutlined: <ScheduleOutlined />,
    SearchOutlined: <SearchOutlined />,
    SettingOutlined: <SettingOutlined />,
    ShareAltOutlined: <ShareAltOutlined />,
    ShoppingCartOutlined: <ShoppingCartOutlined />,
    ShoppingOutlined: <ShoppingOutlined />,
    SketchOutlined: <SketchOutlined />,
    SkinOutlined: <SkinOutlined />,
    SlackOutlined: <SlackOutlined />,
    SlidersOutlined: <SlidersOutlined />,
    SplitCellsOutlined: <SplitCellsOutlined />,
    StarOutlined: <StarOutlined />,
    SunOutlined: <SunOutlined />,
    TableOutlined: <TableOutlined />,
    TeamOutlined: <TeamOutlined />,
    ThunderboltOutlined: <ThunderboltOutlined />,
    ToolOutlined: <ToolOutlined />,
    ToTopOutlined: <ToTopOutlined />,
    TrademarkOutlined: <TrademarkOutlined />,
    TranslationOutlined: <TranslationOutlined />,
    TruckOutlined: <TruckOutlined />,
    UsbOutlined: <UsbOutlined />,
    UserAddOutlined: <UserAddOutlined />,
    UserDeleteOutlined: <UserDeleteOutlined />,
    UsergroupAddOutlined: <UsergroupAddOutlined />,
    UsergroupDeleteOutlined: <UsergroupDeleteOutlined />,
    UserOutlined: <UserOutlined />,
    UserSwitchOutlined: <UserSwitchOutlined />,
    VerifiedOutlined: <VerifiedOutlined />,
    WalletOutlined: <WalletOutlined />,
    WarningOutlined: <WarningOutlined />,
    WechatOutlined: <WechatOutlined />,
    WhatsAppOutlined: <WhatsAppOutlined />,
    WifiOutlined: <WifiOutlined />,
    WindowsOutlined: <WindowsOutlined />,
    WomanOutlined: <WomanOutlined />,
    YoutubeOutlined: <YoutubeOutlined />,

};

const { Text } = Typography;

// 導出圖標映射對象
export const getIconMapping = () => iconMapping;

// 導出一個函數來獲取圖標名稱列表（用於 Select 組件）
export const getIconNames = () => Object.keys(iconMapping);

// 導出一個組件來渲染圖標（用於表格和菜單預覽）
export const IconRenderer = ({ icon, customIcon }) => {
    if (customIcon) {
        return <Avatar src={customIcon} size={20} />;
    }
    if (icon && iconMapping[icon]) {
        return (
            <Space>
                {iconMapping[icon]}
                <Text>{icon}</Text>
            </Space>
        );
    }
    return '無';
};